2022-05-10 17:20:18,341 WARNING: [Errno 2] No such file or directory: '/Documents/Shard/CNC/Map Files/Maps/wargame_provinces.png'
2022-05-10 17:25:20,385 WARNING: [Errno 2] No such file or directory: '/Documents/Shard/CNC/Map Files/Maps/wargame_provinces.png'
2022-05-10 17:26:58,271 WARNING: [Errno 2] No such file or directory: '/Documents/Shard/CNC/Map Files/Maps/wargame_provinces.png'
2022-05-10 17:33:21,851 WARNING: [Errno 2] No such file or directory: '~/Documents/Shard/CNC/Map Files/Maps/wargame_provinces.png'
2022-05-10 17:33:43,082 WARNING: [Errno 2] No such file or directory: '~/Documents/Shard/CNC/Map Files/Maps/wargame_provinces.png'
2022-05-10 17:36:36,895 WARNING: [Errno 2] No such file or directory: '/root/Documents/Shard/CNC/Map Files\\Maps\\wargame_nations_map.png'
2022-05-10 17:46:41,828 WARNING: 
2022-05-10 17:47:57,187 WARNING: [Errno 2] No such file or directory: '/root/Documents/Shard/CNC/Interaction Files/293518673417732098.txt'
2022-05-10 21:45:41,644 WARNING: relation "mod_logs" does not exist
2022-06-09 19:38:08,458 WARNING: cnc_construct: 
2022-06-09 19:42:00,975 WARNING: cnc_construct: 
2022-06-09 19:52:07,223 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 2149, in cnc_construct
    raise commands.UserInputError
discord.ext.commands.errors.UserInputError

2022-06-09 19:54:37,051 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 2149, in cnc_construct
    raise commands.UserInputError
discord.ext.commands.errors.UserInputError

2022-06-10 22:02:44,939 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 1773, in cnc_bank
    ownedprovinces = [p for p in userinfo['provinces_owned']]
TypeError: 'NoneType' object is not subscriptable

2022-06-11 07:51:42,877 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4287, in cncstartloop
    await shardchannel.send(f"Turn loop until {update.strftime('%d %a %Y at %H:%M:%S %Z%z')}.")
AttributeError: 'NoneType' object has no attribute 'send'

2022-06-11 08:23:00,406 WARNING: NoneType: None

2022-06-11 08:30:07,250 WARNING: NoneType: None

2022-06-11 08:30:10,239 WARNING: NoneType: None

2022-06-11 08:31:21,262 WARNING: NoneType: None

2022-06-11 08:32:18,165 WARNING: NoneType: None

2022-06-11 08:34:42,211 WARNING: NoneType: None

2022-06-11 08:42:13,468 WARNING: NoneType: None

2022-06-11 08:44:39,264 WARNING: NoneType: None

2022-06-11 08:50:48,003 WARNING: NoneType: None

2022-06-11 08:53:40,094 WARNING: NoneType: None

2022-06-11 09:14:02,134 WARNING: NoneType: None

2022-06-11 09:14:04,725 WARNING: NoneType: None

2022-06-11 09:15:39,399 WARNING: NoneType: None

2022-06-11 11:43:43,845 WARNING: NoneType: None

2022-06-11 12:03:17,392 WARNING: NoneType: None

2022-06-11 12:10:34,724 WARNING: column "undeployed_troops" of relation "cncusers" does not exist
2022-06-11 12:11:39,457 WARNING: 'NoneType' object is not subscriptable
2022-06-11 12:13:34,124 WARNING: 'NoneType' object is not subscriptable
2022-06-11 12:56:24,951 WARNING: Command "cnc_withraw_all" is not found
2022-06-11 12:56:28,785 WARNING: Command "cncwa" is not found
2022-06-11 15:55:02,759 WARNING: NoneType: None

2022-06-12 10:57:42,343 WARNING: Command "cnxdv" is not found
2022-06-12 12:10:24,918 WARNING: Command "cnc" is not found
2022-06-12 12:18:49,567 WARNING: 'NoneType' object is not subscriptable
2022-06-12 17:14:33,969 WARNING: Command "yes" is not found
2022-06-12 17:25:28,554 WARNING: 'Message' object has no attribute 'reaction_add'
2022-06-12 17:36:22,851 WARNING: Command "atop" is not found
2022-06-12 23:44:36,807 WARNING: Command "cnc_mao" is not found
2022-06-13 00:33:32,601 WARNING: Command "cnc_constuct" is not found
2022-06-13 05:02:07,125 WARNING: Command "template" is not found
2022-06-13 05:02:22,577 WARNING: Command "instructions" is not found
2022-06-13 06:35:22,483 WARNING: Command "nation_map" is not found
2022-06-13 11:38:23,852 WARNING: 'NoneType' object is not subscriptable
2022-06-13 12:08:41,875 WARNING: Command "cnc_great_power" is not found
2022-06-13 12:21:35,053 WARNING: Command "cnc_view_interactions" is not found
2022-06-14 05:01:47,330 WARNING: Command "cnc_contruct" is not found
2022-06-14 05:03:29,306 WARNING: Command "cnCbg" is not found
2022-06-14 12:00:01,079 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 3846, in turn_loop
    userinfo['username'], closed_route['nation'])
TypeError: 'NoneType' object is not subscriptable

2022-06-14 12:13:05,779 WARNING: 'NoneType' object is not subscriptable
2022-06-14 12:22:07,089 WARNING: Command "cnc_view_interactions" is not found
2022-06-14 12:22:12,512 WARNING: Command "cnc" is not found
2022-06-14 12:22:14,933 WARNING: is_owner() missing 1 required positional argument: 'user'
2022-06-14 12:22:24,703 WARNING: is_owner() missing 1 required positional argument: 'user'
2022-06-14 12:22:27,310 WARNING: is_owner() missing 1 required positional argument: 'user'
2022-06-15 13:18:38,826 WARNING: Command "cnc_withdraw_al" is not found
2022-06-17 16:31:37,195 WARNING: Command "ccnb" is not found
2022-06-17 16:49:10,787 WARNING: Command "cncv=b" is not found
2022-06-18 09:42:26,865 WARNING: Command "cncbv" is not found
2022-06-18 09:42:28,957 WARNING: Command "cnv" is not found
2022-06-18 09:45:21,893 WARNING: Command "cnc_contruct" is not found
2022-06-19 10:21:03,501 WARNING: Command "cnxv" is not found
2022-06-19 22:31:28,748 WARNING: Command "cnc_trade" is not found
2022-06-19 22:31:45,023 WARNING: Command "cnc_trade_" is not found
2022-06-19 22:31:52,556 WARNING: Command "cnc_trade_" is not found
2022-06-19 22:33:19,969 WARNING: Command "cnc_trade_route_crea" is not found
2022-06-20 05:43:22,815 WARNING: Command "instructions" is not found
2022-06-20 05:43:33,126 WARNING: Command "instructions" is not found
2022-06-20 23:14:35,209 WARNING: Command "cnc_constrcuct" is not found
2022-06-20 23:18:04,744 WARNING: Command "cnc_construct3" is not found
2022-06-20 23:52:39,287 WARNING: Command "cnc_view_pending_interaction" is not found
2022-06-20 23:53:06,172 WARNING: Command "cnc_view_pending_interaction" is not found
2022-06-21 00:06:24,948 WARNING: Command "cnc_interactipn" is not found
2022-06-21 00:07:39,883 WARNING: Command "cnc_interaction988656297413070871" is not found
2022-06-21 00:12:42,077 WARNING: Command "cnc_focus_" is not found
2022-06-21 00:12:53,575 WARNING: Command "cnc_focus_e" is not found
2022-06-21 00:13:03,157 WARNING: Command "cnc_help" is not found
2022-06-21 00:14:01,427 WARNING: Command "cnc_change_focus" is not found
2022-06-21 00:14:16,678 WARNING: Command "cnc_change_focus_e" is not found
2022-06-24 01:53:03,230 WARNING: Command "p" is not found
2022-06-24 04:58:36,903 WARNING: 'Message' object has no attribute 'reaction_add'
2022-06-24 11:26:55,303 WARNING: Command "rankm" is not found
2022-06-25 10:39:23,146 WARNING: Command "cnc_consdtruct" is not found
2022-06-25 13:22:25,330 WARNING: Command "cnc_focus" is not found
2022-06-25 13:22:28,733 WARNING: Command "cnc_change" is not found
2022-06-25 13:22:36,340 WARNING: Command "cnc" is not found
2022-06-25 13:22:42,123 WARNING: Command "cnc_help" is not found
2022-06-25 13:25:44,975 WARNING: Command "cncdvf" is not found
2022-06-25 14:57:42,456 WARNING: 'NoneType' object is not subscriptable
2022-06-25 14:57:47,122 WARNING: 'NoneType' object is not subscriptable
2022-06-25 15:33:02,599 WARNING: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.2.value: This field is required
2022-06-26 04:00:21,518 WARNING: Command "nation_map" is not found
2022-06-26 04:37:14,049 WARNING: Command "cnc_declar" is not found
2022-06-27 05:37:38,926 WARNING: Command "cnc_revamper" is not found
2022-06-28 01:01:44,469 WARNING: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.4.value: This field is required
2022-06-28 01:02:02,752 WARNING: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.4.value: This field is required
2022-06-28 01:41:38,670 WARNING: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.4.value: This field is required
2022-06-28 02:37:25,541 WARNING: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.4.value: This field is required
2022-06-28 02:37:34,956 WARNING: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.4.value: This field is required
2022-06-28 02:50:45,472 WARNING: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.4.value: This field is required
2022-06-28 10:48:36,736 WARNING: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.4.value: This field is required
2022-06-28 12:11:53,184 WARNING: 'NoneType' object is not subscriptable
2022-06-28 12:12:43,958 WARNING: 'occupier_id'
2022-06-29 00:00:10,978 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 3896, in turn_loop
    troops_remaining = p_info['troops'] - (p_info['manpower'] * 2)
TypeError: 'NoneType' object is not subscriptable

2022-06-29 12:22:43,644 WARNING: inconsistent types deduced for parameter $1
DETAIL:  bigint versus text
2022-06-29 12:23:09,015 WARNING: inconsistent types deduced for parameter $1
DETAIL:  bigint versus text
2022-06-29 12:23:24,053 WARNING: inconsistent types deduced for parameter $1
DETAIL:  bigint versus text
2022-06-29 12:24:45,355 WARNING: inconsistent types deduced for parameter $1
DETAIL:  bigint versus text
2022-06-29 12:26:43,174 WARNING: Command "cncwa" is not found
2022-06-29 12:29:01,674 WARNING: inconsistent types deduced for parameter $1
DETAIL:  bigint versus text
2022-06-29 12:29:52,861 WARNING: inconsistent types deduced for parameter $1
DETAIL:  bigint versus text
2022-06-29 12:34:42,729 WARNING: inconsistent types deduced for parameter $1
DETAIL:  bigint versus text
2022-06-29 16:12:46,575 WARNING: cnca: inconsistent types deduced for parameter $1
DETAIL:  bigint versus text
2022-06-29 16:16:34,343 WARNING: cnc_withdraw)all: Command "cnc_withdraw)all" is not found
2022-06-29 20:49:26,489 WARNING: cncw: 'NoneType' object is not subscriptable
2022-06-30 00:08:06,132 WARNING: cnc_withdraw_alll: Command "cnc_withdraw_alll" is not found
2022-06-30 23:06:04,438 WARNING: cnc_deplpy: Command "cnc_deplpy" is not found
2022-07-01 01:41:03,909 WARNING: cnc_withdraw_alll: Command "cnc_withdraw_alll" is not found
2022-07-01 09:21:52,635 WARNING: cnc_deploy: 'occupier_id'
2022-07-01 11:14:04,474 WARNING: 15: Command "15" is not found
2022-07-01 18:22:48,356 WARNING: cnc_declare: column "trade" of relation "relations" does not exist
2022-07-01 18:27:44,409 WARNING: cnc_mass_deploy: column "undeployed_troops" of relation "cncusers" does not exist
2022-07-01 18:27:57,421 WARNING: cnc_declare: the server expects 2 arguments for this query, 4 were passed
HINT:  Check the query against the passed list of arguments.
2022-07-01 18:31:41,859 WARNING: cnc_declare: column "trade" of relation "cncusers" does not exist
2022-07-01 18:32:09,456 WARNING: cnva: Command "cnva" is not found
2022-07-01 18:32:41,693 WARNING: cnc_declare: column "trade" of relation "cncusers" does not exist
2022-07-01 18:33:15,825 WARNING: cnc_declare: column "trade" of relation "cncusers" does not exist
2022-07-01 18:33:28,016 WARNING: cnc_mass_deploy: 'NoneType' object is not subscriptable
2022-07-01 18:34:37,223 WARNING: cnc_mass_deploy: 'NoneType' object is not subscriptable
2022-07-01 18:34:48,421 WARNING: cnc_mass_deply: Command "cnc_mass_deply" is not found
2022-07-01 18:36:04,724 WARNING: cnc_mass_deploy: 'NoneType' object is not subscriptable
2022-07-01 21:45:26,075 WARNING: cnc_mass_deploy: invalid input for query argument $2: <Record id=451 terrain=0 bordering=[449,... (an integer is required (got type asyncpg.Record))
2022-07-01 21:47:44,066 WARNING: cnc_mass_deploy: invalid input for query argument $2: <Record id=451 terrain=0 bordering=[449,... (an integer is required (got type asyncpg.Record))
2022-07-01 21:55:23,408 WARNING: cncp212: Command "cncp212" is not found
2022-07-01 21:58:49,701 WARNING: cncv: list.remove(x): x not in list
2022-07-01 21:58:59,152 WARNING: cncv: list.remove(x): x not in list
2022-07-01 22:08:16,109 WARNING: cnc_declare: column "trade" of relation "cncusers" does not exist
2022-07-01 22:12:56,507 WARNING: cnc_delcare: Command "cnc_delcare" is not found
2022-07-01 22:13:08,730 WARNING: cnc_declare: invalid input for query argument $1: 6 (a sized iterable container expected (got type 'int'))
2022-07-02 04:07:45,078 WARNING: cnc_change_focus: Command "cnc_change_focus" is not found
2022-07-02 04:08:35,595 WARNING: cnc_focus: Command "cnc_focus" is not found
2022-07-02 04:13:44,462 WARNING: cnc_move_capital: Command "cnc_move_capital" is not found
2022-07-02 04:15:45,690 WARNING: cnc: Command "cnc" is not found
2022-07-02 04:15:48,175 WARNING: cnch: Command "cnch" is not found
2022-07-02 04:15:52,187 WARNING: cnchelp: Command "cnchelp" is not found
2022-07-02 04:15:56,018 WARNING: cnc_help: Command "cnc_help" is not found
2022-07-02 04:44:28,311 WARNING: verify: Command "verify" is not found
2022-07-02 05:53:31,486 WARNING: cncd: 'occupier_id'
2022-07-02 06:00:24,415 WARNING: cncd: 'occupier_id'
2022-07-02 06:00:37,987 WARNING: cncd: 'occupier_id'
2022-07-02 06:09:28,306 WARNING: cncd: 'occupier_id'
2022-07-02 06:13:43,993 WARNING: turn: Command "turn" is not found
2022-07-02 06:18:18,172 WARNING: cncwa: Command "cncwa" is not found
2022-07-02 06:22:40,133 WARNING: cnc_help: Command "cnc_help" is not found
2022-07-02 06:22:56,748 WARNING: cnc_HELP: Command "cnc_HELP" is not found
2022-07-02 06:28:48,289 WARNING: cnc_interaction: column "occuiper" does not exist
HINT:  Perhaps you meant to reference the column "provinces.occupier".
2022-07-02 06:31:38,402 WARNING: cnc_contruct: Command "cnc_contruct" is not found
2022-07-02 06:34:02,596 WARNING: cncd: 'occupier_id'
2022-07-02 06:34:49,199 WARNING: cnc_interaction: column "occuiper" does not exist
HINT:  Perhaps you meant to reference the column "provinces.occupier".
2022-07-02 07:35:13,668 WARNING: cnc_interaction: column "occuiper" does not exist
HINT:  Perhaps you meant to reference the column "provinces.occupier".
2022-07-02 10:25:33,069 WARNING: cnc_change_focus: Command "cnc_change_focus" is not found
2022-07-02 10:35:13,906 WARNING: helpcnc: Command "helpcnc" is not found
2022-07-02 11:57:39,666 WARNING: $cnca: Command "$cnca" is not found
2022-07-02 12:00:19,128 WARNING: cncd: 'occupier_id'
2022-07-02 12:00:45,172 WARNING: cncd: 'occupier_id'
2022-07-02 12:13:02,980 WARNING: cncd: 'occupier_id'
2022-07-02 12:13:08,353 WARNING: cncwa: Command "cncwa" is not found
2022-07-02 18:50:48,342 WARNING: cnc: Command "cnc" is not found
2022-07-02 23:32:08,951 WARNING: cnc_withdraw_ALL: Command "cnc_withdraw_ALL" is not found
2022-07-02 23:55:27,301 WARNING: cncv\: Command "cncv\" is not found
2022-07-03 00:40:39,277 WARNING: cnc_set_focus: Command "cnc_set_focus" is not found
2022-07-03 00:43:08,236 WARNING: cnc_edit_focus: Command "cnc_edit_focus" is not found
2022-07-03 03:44:33,250 WARNING: cnca: 'NoneType' object is not subscriptable
2022-07-03 06:10:23,526 WARNING: cnncw: Command "cnncw" is not found
2022-07-03 06:49:48,549 WARNING: cnc_deplpy: Command "cnc_deplpy" is not found
2022-07-03 07:58:15,248 WARNING: cnc_expidition: Command "cnc_expidition" is not found
2022-07-03 08:04:20,133 WARNING: cnc_release: list.remove(x): x not in list
2022-07-03 08:07:43,553 WARNING: cncsb: Command "cncsb" is not found
2022-07-03 08:44:08,359 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 2439, in cnc_attack
    if war['relation'] != 'war':
TypeError: 'NoneType' object is not subscriptable

2022-07-03 09:05:15,647 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 897, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-07-03 11:13:51,211 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_declare,," is not found

2022-07-04 00:00:02,418 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 3912, in turn_loop
    troops_remaining = p_info['troops'] - (p_info['manpower'] * 2)
TypeError: 'NoneType' object is not subscriptable

2022-07-04 03:27:19,495 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-04 03:28:31,367 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFile.py", line 239, in load
    s = read(self.decodermaxblock)
  File "/usr/local/lib/python3.8/dist-packages/PIL/PngImagePlugin.py", line 923, in load_read
    cid, pos, length = self.png.read()
  File "/usr/local/lib/python3.8/dist-packages/PIL/PngImagePlugin.py", line 189, in read
    length = i32(s)
  File "/usr/local/lib/python3.8/dist-packages/PIL/_binary.py", line 85, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 3050, in cnc_map
    await loop.run_in_executor(None, self.add_ids)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 133, in add_ids
    bmap = Image.open(fr"{self.map_directory}/Maps/wargame_provinces.png").convert("RGBA")
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 934, in convert
    self.load()
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFile.py", line 245, in load
    raise OSError("image file is truncated") from e
OSError: image file is truncated

2022-07-04 06:01:04,328 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 453, in cnc_detailed_view
    provinceslist.remove(0)
ValueError: list.remove(x): x not in list

2022-07-04 06:01:21,231 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_peace,," is not found

2022-07-04 06:04:13,324 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 453, in cnc_detailed_view
    provinceslist.remove(0)
ValueError: list.remove(x): x not in list

2022-07-04 06:04:36,761 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 268, in cnc_view
    provinceslist.remove(0)
ValueError: list.remove(x): x not in list

2022-07-04 06:05:11,762 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_map@" is not found

2022-07-04 09:01:15,309 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_constuct" is not found

2022-07-04 09:01:25,075 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_constuct" is not found

2022-07-04 12:51:52,076 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 367, in cnc_view
    provinceslist.remove(0)
ValueError: list.remove(x): x not in list

2022-07-05 02:30:30,080 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1104, in cnc_offer
    await ctx.send(embed=embed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 506, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.2.value: This field is required

2022-07-05 02:30:51,112 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1104, in cnc_offer
    await ctx.send(embed=embed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 506, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.2.value: This field is required

2022-07-05 11:33:49,071 WARNING: discord.ext.commands.errors.CommandNotFound: Command "nation_map" is not found

2022-07-05 11:35:26,085 WARNING: discord.ext.commands.errors.CommandNotFound: Command "nation" is not found

2022-07-05 11:45:51,644 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_change" is not found

2022-07-05 11:49:34,339 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 848, in cnc_province
    await ctx.send(embed=provinceembed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 506, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.4.value: This field is required

2022-07-05 11:50:19,712 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 848, in cnc_province
    await ctx.send(embed=provinceembed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 506, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.4.value: This field is required

2022-07-05 12:22:45,678 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1104, in cnc_offer
    await ctx.send(embed=embed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 506, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.2.value: This field is required

2022-07-05 12:22:52,740 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1104, in cnc_offer
    await ctx.send(embed=embed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 506, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.2.value: This field is required

2022-07-05 12:23:35,214 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1104, in cnc_offer
    await ctx.send(embed=embed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 506, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.2.value: This field is required

2022-07-05 12:38:12,097 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 3829, in cnc_owned_check
    owned_provinces = await conn.fetch('''SELECT * FROM provinces WHERE owner_id = $1;''', u['id'])
KeyError: 'id'

2022-07-05 12:46:09,281 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_change" is not found

2022-07-05 12:46:20,420 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_change" is not found

2022-07-06 05:35:14,859 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_n" is not found

2022-07-06 05:35:35,131 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_change" is not found

2022-07-06 05:35:43,507 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncc" is not found

2022-07-06 06:52:40,011 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_trade" is not found

2022-07-06 06:53:33,643 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_trade_routw" is not found

2022-07-06 07:54:07,143 WARNING: discord.ext.commands.errors.CommandNotFound: Command "CNC_CONSTRUCT" is not found

2022-07-06 07:54:36,392 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1718, in cnc_bank
    ownedprovinces = [p for p in userinfo['provinces_owned']]
TypeError: 'NoneType' object is not subscriptable

2022-07-06 07:54:54,108 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1718, in cnc_bank
    ownedprovinces = [p for p in userinfo['provinces_owned']]
TypeError: 'NoneType' object is not subscriptable

2022-07-06 07:57:10,307 WARNING: discord.ext.commands.errors.CommandNotFound: Command "withdraw" is not found

2022-07-06 07:57:55,264 WARNING: discord.ext.commands.errors.CommandNotFound: Command "deploy" is not found

2022-07-06 08:02:20,862 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncw_all" is not found

2022-07-06 08:10:28,475 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_changem" is not found

2022-07-06 08:10:37,394 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_change_c" is not found

2022-07-06 10:32:52,479 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_recuit" is not found

2022-07-06 10:33:10,900 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_recuit" is not found

2022-07-06 11:05:13,106 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_edit_focus" is not found

2022-07-06 12:27:08,300 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnct" is not found

2022-07-06 12:40:57,348 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_hell" is not found

2022-07-06 12:41:04,568 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_help" is not found

2022-07-06 17:20:09,215 WARNING: Cannot connect to host www.nationstates.net:443 ssl:default [Temporary failure in name resolution]
2022-07-07 07:37:11,495 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-07 08:18:54,125 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnct" is not found

2022-07-07 10:47:10,672 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnct" is not found

2022-07-07 12:05:02,747 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncw_all" is not found

2022-07-07 12:07:08,344 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncwa" is not found

2022-07-07 12:58:00,302 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_decalre" is not found

2022-07-07 15:59:24,691 WARNING: discord.ext.commands.errors.CommandNotFound: Command "nation_map" is not found

2022-07-07 17:02:52,042 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-08 04:59:33,898 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnf_map" is not found

2022-07-08 04:59:57,172 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncp97" is not found

2022-07-08 05:05:20,954 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-08 05:08:49,740 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncmap" is not found

2022-07-08 05:24:09,176 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnct" is not found

2022-07-08 13:13:32,621 WARNING: discord.ext.commands.errors.CommandNotFound: Command "sto" is not found

2022-07-08 13:22:53,692 WARNING: discord.ext.commands.errors.CommandNotFound: Command "deploy" is not found

2022-07-09 00:14:26,343 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_withdraw_al" is not found

2022-07-09 00:18:42,203 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_trade" is not found

2022-07-09 10:02:49,860 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncn" is not found

2022-07-09 10:12:32,262 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-07-09 10:14:48,656 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ineraction" is not found

2022-07-09 10:19:01,553 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnx_ineraction" is not found

2022-07-09 10:19:16,599 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ineraction" is not found

2022-07-09 10:20:52,533 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ineraction" is not found

2022-07-09 10:26:22,139 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFile.py", line 239, in load
    s = read(self.decodermaxblock)
  File "/usr/local/lib/python3.8/dist-packages/PIL/PngImagePlugin.py", line 923, in load_read
    cid, pos, length = self.png.read()
  File "/usr/local/lib/python3.8/dist-packages/PIL/PngImagePlugin.py", line 189, in read
    length = i32(s)
  File "/usr/local/lib/python3.8/dist-packages/PIL/_binary.py", line 85, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 3062, in cnc_map
    await loop.run_in_executor(None, self.add_ids)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 133, in add_ids
    bmap = Image.open(fr"{self.map_directory}/Maps/wargame_provinces.png").convert("RGBA")
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 934, in convert
    self.load()
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFile.py", line 245, in load
    raise OSError("image file is truncated") from e
OSError: image file is truncated

2022-07-09 10:58:49,752 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 375, in cnc_view
    total_troops += p_total_troops['sum']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

2022-07-09 10:59:00,927 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 375, in cnc_view
    total_troops += p_total_troops['sum']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

2022-07-09 10:59:22,921 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 375, in cnc_view
    total_troops += p_total_troops['sum']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

2022-07-09 11:03:07,942 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 276, in cnc_view
    total_troops += total_troops_raw['sum']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

2022-07-09 11:07:29,892 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 277, in cnc_view
    total_troops += total_troops_raw['sum']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

2022-07-09 11:08:57,863 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1720, in cnc_bank
    ownedprovinces = [p for p in userinfo['provinces_owned']]
TypeError: 'NoneType' object is not subscriptable

2022-07-09 11:13:33,282 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_build" is not found

2022-07-09 11:13:40,040 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncc" is not found

2022-07-09 14:21:29,579 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_deploy_all" is not found

2022-07-10 00:58:13,906 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-10 12:16:06,352 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncwa" is not found

2022-07-10 12:17:12,578 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncq" is not found

2022-07-10 13:02:01,352 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_mpa" is not found

2022-07-11 00:26:20,083 WARNING: discord.ext.commands.errors.CommandNotFound: Command "editcurrency" is not found

2022-07-11 07:46:31,048 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_gp" is not found

2022-07-11 14:18:51,986 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_expeditionary" is not found

2022-07-11 14:18:54,813 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnch" is not found

2022-07-11 14:23:07,777 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma" is not found

2022-07-11 14:31:33,587 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_movr" is not found

2022-07-11 14:31:54,052 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_move_all" is not found

2022-07-11 14:36:42,172 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnca54" is not found

2022-07-11 14:36:51,610 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_.ap" is not found

2022-07-11 15:08:01,261 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc-map" is not found

2022-07-11 15:19:36,709 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-12 02:52:13,360 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-12 06:11:08,865 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_rename" is not found

2022-07-12 07:11:38,736 WARNING: discord.ext.commands.errors.CommandNotFound: Command "rleoad" is not found

2022-07-12 10:00:40,023 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnxa" is not found

2022-07-12 13:25:22,170 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-07-12 13:39:11,782 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-07-12 21:25:28,095 WARNING: discord.ext.commands.errors.CommandNotFound: Command "livestock" is not found

2022-07-12 21:25:34,185 WARNING: discord.ext.commands.errors.CommandNotFound: Command "livestocks" is not found

2022-07-12 23:33:19,987 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncbUnion_Of_Orien_Olkanania" is not found

2022-07-12 23:35:47,704 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1761, in cnc_bank
    await ctx.send(embed=bankembed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 444, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]

2022-07-14 01:24:39,510 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cmcdv" is not found

2022-07-14 06:32:57,629 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-14 08:37:40,930 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-14 08:51:35,628 WARNING: discord.ext.commands.errors.CommandNotFound: Command "remind_me" is not found

2022-07-15 05:45:27,817 WARNING: discord.ext.commands.errors.CommandNotFound: Command "ccnca" is not found

2022-07-15 05:46:17,701 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnncd" is not found

2022-07-15 05:46:20,658 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-15 05:47:34,931 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_great_power" is not found

2022-07-15 08:51:48,184 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnchp" is not found

2022-07-15 08:52:24,019 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_alliance_Crsytaliz,," is not found

2022-07-16 02:24:34,467 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cbcv" is not found

2022-07-16 02:32:33,495 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_pending" is not found

2022-07-16 02:32:39,994 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncv_pending" is not found

2022-07-16 02:33:52,620 WARNING: discord.ext.commands.errors.CommandNotFound: Command "view_pending" is not found

2022-07-16 06:43:15,010 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-16 07:00:13,021 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_inetraction" is not found

2022-07-16 07:01:50,952 WARNING: Traceback (most recent call last):
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
  File "asyncpg/protocol/codecs/base.pyx", line 206, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg/protocol/codecs/base.pyx", line 111, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg/pgproto/./codecs/int.pyx", line 111, in asyncpg.pgproto.pgproto.int8_encode
OverflowError: value out of int64 range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1118, in cnc_interaction
    pending_int = await conn.fetchrow('''SELECT * FROM pending_interactions WHERE id = $1;''',
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 615, in fetchrow
    return await con.fetchrow(query, *args, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 679, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1731, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 183, in bind_execute
  File "asyncpg/protocol/prepared_stmt.pyx", line 197, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $1: 9978202655411137546 (value out of int64 range)

2022-07-17 10:15:45,353 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-19 10:25:27,625 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-07-19 10:25:32,623 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnxa" is not found

2022-07-19 10:27:46,901 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncw_all" is not found

2022-07-23 18:02:17,603 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 2258, in cnc_withdraw
    if amount > provinceinfo['troops']:
TypeError: 'NoneType' object is not subscriptable

2022-07-23 18:25:33,415 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncp86" is not found

2022-07-24 03:24:29,535 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncwa" is not found

2022-07-25 16:21:36,239 WARNING: discord.ext.commands.errors.CommandNotFound: Command "rank_m" is not found

2022-07-26 12:16:16,751 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/base.py", line 27, in info
    infoembed.add_field(name="Current version", value=f"{self.bot.version} {self.bot.version_name}")
AttributeError: 'Shard' object has no attribute 'version_name'

2022-07-26 12:24:34,436 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 333, in cnc_view
    wars = ', '.join(str(w['nation']) for w in wars)
  File "/root/Documents/Shard/cogs/cnc.py", line 333, in <genexpr>
    wars = ', '.join(str(w['nation']) for w in wars)
KeyError: 'nation'

2022-07-26 12:34:54,227 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1157, in cnc_view_interaction
    interactions_file.write(interactions_text)
TypeError: a bytes-like object is required, not 'str'

2022-07-26 12:36:55,651 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1159, in cnc_view_interaction
    await author.send(file=discord.File(interactions_file, f"Interactions Log for {author.id}.txt"))
  File "/usr/local/lib/python3.8/dist-packages/discord/file.py", line 91, in __init__
    if not (fp.seekable() and fp.readable()):
ValueError: I/O operation on closed file

2022-07-26 12:37:44,268 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1158, in cnc_view_interaction
    await author.send(file=discord.File(interactions_file, f"Interactions Log for {author.id}.txt"))
  File "/usr/local/lib/python3.8/dist-packages/discord/file.py", line 92, in __init__
    raise ValueError(f'File buffer {fp!r} must be seekable and readable')
ValueError: File buffer <_io.TextIOWrapper name='/root/Documents/Shard/CNC/Interaction Files/293518673417732098.txt' mode='w' encoding='UTF-8'> must be seekable and readable

2022-07-26 12:39:28,654 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1159, in cnc_view_interaction
    await author.send(file=discord.File(interactions_file, f"Interactions Log for {author.id}.txt"))
  File "/usr/local/lib/python3.8/dist-packages/discord/file.py", line 92, in __init__
    raise ValueError(f'File buffer {fp!r} must be seekable and readable')
ValueError: File buffer <_io.TextIOWrapper name='/root/Documents/Shard/CNC/Interaction Files/293518673417732098.txt' mode='w' encoding='UTF-8'> must be seekable and readable

2022-07-26 12:46:45,721 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_check_provinces" is not found

2022-07-26 13:51:54,477 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncdb" is not found

2022-07-26 18:00:38,716 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4099, in turn_loop
    forts = await conn.fetchrow(''''SELECT count(*) FROM provinces WHERE owner_id = $1 AND fort = True;''',
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 615, in fetchrow
    return await con.fetchrow(query, *args, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 679, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.PostgresSyntaxError: unterminated quoted string at or near "'SELECT count(*) FROM provinces WHERE owner_id = $1 AND fort = True;"

2022-07-26 22:06:24,488 WARNING: discord.ext.commands.errors.CommandNotFound: Command "15k" is not found

2022-07-27 00:00:38,725 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4099, in turn_loop
    forts = await conn.fetchrow(''''SELECT count(*) FROM provinces WHERE owner_id = $1 AND fort = True;''',
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 615, in fetchrow
    return await con.fetchrow(query, *args, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 679, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.PostgresSyntaxError: unterminated quoted string at or near "'SELECT count(*) FROM provinces WHERE owner_id = $1 AND fort = True;"

2022-07-27 06:00:38,782 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4099, in turn_loop
    forts = await conn.fetchrow(''''SELECT count(*) FROM provinces WHERE owner_id = $1 AND fort = True;''',
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 615, in fetchrow
    return await con.fetchrow(query, *args, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 679, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.PostgresSyntaxError: unterminated quoted string at or near "'SELECT count(*) FROM provinces WHERE owner_id = $1 AND fort = True;"

2022-07-27 12:00:01,055 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4101, in turn_loop
    if cities > citylimit:
TypeError: '>' not supported between instances of 'asyncpg.Record' and 'int'

2022-07-27 12:06:37,493 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4498, in cnc_force_turn
    structure_cost += 1000 * (cities - citylimit)
TypeError: unsupported operand type(s) for -: 'asyncpg.Record' and 'int'

2022-07-27 12:09:42,701 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4498, in cnc_force_turn
    structure_cost += 1000 * (cities - citylimit)
TypeError: unsupported operand type(s) for -: 'asyncpg.Record' and 'int'

2022-07-27 12:11:15,873 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4809, in cnc_force_turn
    alliances = await conn.fetchrow(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 615, in fetchrow
    return await con.fetchrow(query, *args, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 679, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedColumnError: column "relation" does not exist

2022-07-27 12:12:47,970 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4475, in cnc_force_turn
    forts = await conn.fetchrow(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 615, in fetchrow
    return await con.fetchrow(query, *args, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 679, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.PostgresSyntaxError: unterminated quoted string at or near "'SELECT count(*) FROM provinces WHERE owner_id = $1 AND fort = True;"

2022-07-27 18:00:47,912 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4077, in turn_loop
    forts = await conn.fetchrow(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 615, in fetchrow
    return await con.fetchrow(query, *args, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 679, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.PostgresSyntaxError: unterminated quoted string at or near "'SELECT count(*) FROM provinces WHERE owner_id = $1 AND fort = True;"

2022-07-30 02:17:34,548 WARNING: discord.ext.commands.errors.CommandNotFound: Command "rank_m" is not found

2022-07-30 03:46:38,730 WARNING: discord.ext.commands.errors.CommandNotFound: Command "rank_m" is not found

2022-07-30 08:09:11,997 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncwa" is not found

2022-07-31 08:24:20,964 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_gp" is not found

2022-07-31 21:51:51,796 WARNING: discord.ext.commands.errors.CommandNotFound: Command "br" is not found

2022-08-02 12:52:34,952 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncg0" is not found

2022-08-04 13:27:40,752 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnxv" is not found

2022-08-05 17:37:11,803 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-08-06 12:04:57,044 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_trade" is not found

2022-08-06 12:05:18,382 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_trade" is not found

2022-08-07 01:03:43,390 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc" is not found

2022-08-07 20:00:15,453 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_offer_peace" is not found

2022-08-08 09:40:58,014 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-08-08 14:08:41,849 WARNING: discord.ext.commands.errors.CommandNotFound: Command "n" is not found

2022-08-08 14:37:52,906 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-08-14 18:32:25,833 WARNING: discord.ext.commands.errors.CommandNotFound: Command "pprc" is not found

2022-08-14 18:32:31,588 WARNING: discord.ext.commands.errors.CommandNotFound: Command "pprc2" is not found

2022-08-15 10:41:42,253 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_tech" is not found

2022-08-22 18:10:51,815 WARNING: discord.ext.commands.errors.CommandNotFound: Command "map" is not found

2022-08-22 18:40:43,962 WARNING: discord.ext.commands.errors.CommandNotFound: Command "map" is not found

2022-09-03 06:09:26,200 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncs" is not found

2022-09-03 06:09:32,182 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncs" is not found

2022-09-03 06:13:19,985 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnda" is not found

2022-09-03 06:20:16,391 WARNING: You do not have the moderator role!
2022-09-03 06:20:31,210 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_commands" is not found

2022-09-03 06:42:52,420 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnct" is not found

2022-09-03 06:43:01,243 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1126, in cnc_transfer
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-03 06:43:30,415 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1126, in cnc_transfer
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-03 06:43:40,484 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnf_tramsfer" is not found

2022-09-03 06:43:49,953 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1126, in cnc_transfer
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-03 06:45:48,081 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_gp" is not found

2022-09-03 06:46:01,192 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_gp" is not found

2022-09-03 06:46:07,687 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_greatpowers" is not found

2022-09-03 06:51:40,912 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1007, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-03 06:52:00,024 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1007, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-03 16:52:41,110 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnda" is not found

2022-09-05 12:17:07,796 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_peace_treaty" is not found

2022-09-05 12:22:36,030 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1288, in cnc_interaction
    troops+owner_color['undeployed'], owner_color['user_id'])
TypeError: string indices must be integers

2022-09-05 12:24:26,053 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-09-05 12:24:28,804 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-09-05 12:24:38,647 WARNING: discord.ext.commands.errors.CommandNotFound: Command "CNC_MAP" is not found

2022-09-05 12:26:57,348 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_gp" is not found

2022-09-05 12:27:13,677 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_greatpowrrs" is not found

2022-09-05 12:28:29,431 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-09-05 12:34:55,012 WARNING: discord.ext.commands.errors.CommandNotFound: Command "fnfa" is not found

2022-09-05 12:57:01,094 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnct" is not found

2022-09-05 13:01:38,051 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_view_offwr" is not found

2022-09-05 13:24:08,361 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1007, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-05 13:24:12,738 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1007, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-05 13:24:18,208 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1007, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-05 13:24:28,340 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1007, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-05 13:24:34,744 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1007, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-05 13:24:48,330 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1007, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-05 13:24:56,146 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-09-05 13:31:36,880 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 1007, in cnc_release
    ownedlist.remove(provinceid)
ValueError: list.remove(x): x not in list

2022-09-05 14:43:57,755 WARNING: discord.ext.commands.errors.CommandNotFound: Command "recruit#" is not found

2022-09-06 00:00:09,927 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4298, in turn_loop
    (randint((p_info['manpower']) / 2, p_info['manpower']))
  File "/usr/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.8/random.py", line 212, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

2022-09-06 06:00:05,881 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4298, in turn_loop
    (randint((p_info['manpower']) / 2, p_info['manpower']))
  File "/usr/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.8/random.py", line 212, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

2022-09-06 12:00:03,650 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4298, in turn_loop
    (randint((p_info['manpower']) / 2, p_info['manpower']))
  File "/usr/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.8/random.py", line 212, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

2022-09-06 12:22:49,451 WARNING: Traceback (most recent call last):
  File "/root/Documents/Shard/cogs/cnc.py", line 4696, in cnc_force_turn
    (randint((p_info['manpower']) / 2, p_info['manpower']))
  File "/usr/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.8/random.py", line 212, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

2022-09-06 12:33:37,881 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_deploy_all" is not found

2022-09-06 12:35:33,136 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_releasw" is not found

2022-09-06 12:37:01,330 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 364, in cnc_view
    await ctx.send(embed=cncuserembed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 506, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: This field is required

2022-09-06 12:37:05,190 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 364, in cnc_view
    await ctx.send(embed=cncuserembed)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/context.py", line 767, in send
    return await super().send(
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 1537, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 506, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: This field is required

2022-09-06 12:37:11,705 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncc" is not found

2022-09-06 12:43:56,477 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_ma0" is not found

2022-09-06 12:44:43,187 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncmv" is not found

2022-09-06 12:44:51,086 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncpv" is not found

2022-09-07 02:23:08,531 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncpv" is not found

2022-09-07 02:23:17,703 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncev" is not found

2022-09-07 02:23:23,429 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncav" is not found

2022-09-07 10:08:25,203 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 2284, in cnc_construct
    if userinfo['capital_move'] == turn['data_value']:
TypeError: 'NoneType' object is not subscriptable

2022-09-07 10:10:03,339 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 2284, in cnc_construct
    if userinfo['capital_move'] == turn['data_value']:
TypeError: 'NoneType' object is not subscriptable

2022-09-09 12:52:30,976 WARNING: discord.ext.commands.errors.CommandNotFound: Command "view" is not found

2022-09-09 13:56:12,440 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cmds" is not found

2022-09-09 13:56:15,885 WARNING: discord.ext.commands.errors.CommandNotFound: Command "commands" is not found

2022-09-10 05:32:23,789 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_construst" is not found

2022-09-10 05:32:48,608 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 2284, in cnc_construct
    if userinfo['capital_move'] == turn['data_value']:
TypeError: 'NoneType' object is not subscriptable

2022-09-10 05:32:55,332 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cncg" is not found

2022-09-10 05:33:05,186 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 2284, in cnc_construct
    if userinfo['capital_move'] == turn['data_value']:
TypeError: 'NoneType' object is not subscriptable

2022-09-10 19:36:09,330 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_restore" is not found

2022-09-11 16:42:37,425 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_tech" is not found

2022-09-11 16:42:48,690 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_research" is not found

2022-09-11 21:01:40,077 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 301, in cnc_view
    if userinfo["usercolor"] == "":
TypeError: 'NoneType' object is not subscriptable

2022-09-11 21:04:11,684 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 282, in cnc_register
    await tech.effects()
  File "/root/Documents/Shard/cnc_research.py", line 361, in effects
    await conn.execute('''UPDATE cnc_modifiers SET research_mod = research_mod - 0.05
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/pool.py", line 564, in execute
    return await con.execute(query, *args, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 320, in execute
    _, status, _ = await self._execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedColumnError: column "research_mod" does not exist

2022-09-11 21:09:44,980 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 3613, in cnc_wipe_all_data_reset
    names[iterations], choice(production), p['id'])
IndexError: list index out of range

2022-09-11 21:31:37,575 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 301, in cnc_view
    await ctx.send("You are not registered.")
TypeError: 'NoneType' object is not subscriptable

2022-09-11 21:54:20,492 WARNING: discord.ext.commands.errors.CommandNotFound: Command "cnc_tech_tree" is not found

2022-09-11 21:54:31,504 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/Documents/Shard/cogs/cnc.py", line 960, in cnc_tech_tree
    await tech.tree()
  File "/root/Documents/Shard/cnc_research.py", line 407, in tree
    tree = Image.open(fr"C:\Users\jaedo\OneDrive\NationStates BBCode\Thegye Stuff\Meta RP\Tech Tree\Cnc Tech Tree Lines.png").convert("RGBA")
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jaedo\\OneDrive\\NationStates BBCode\\Thegye Stuff\\Meta RP\\Tech Tree\\Cnc Tech Tree Lines.png'

